# Generated by Django 3.2.16 on 2025-12-23 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0004_auto_20251223_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
    ]
