# Generated by Django 3.2.16 on 2025-12-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0005_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthday',
            options={'verbose_name': 'день рождения', 'verbose_name_plural': 'Дни рождения'},
        ),
    ]
